name: Container

on: push

jobs:
  check_docker_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker Version
        run: |
          docker --version
          docker-compose --version

