name: Custom Action

on: push

jobs:
  custom-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/issues
      id: create_issues
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: title to create issue
        body: auto issue created by custom github actions/checkout
        assignees: 'itachiuchihadev'
    - run: |
        echo ${{ steps.create_issues.outputs.issue }}
    - uses: ./.github/actions/hello
      id: greeting
      with:
        who-to-greet: Naruto
    - run: |
        echo "Time: ${{ steps.greeting.outputs.time }}"

      