name: Shell WorkFlow

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Echo Command
        run: echo "First Workflow Working"
      - name: Multiline Command
        run: |
          node -v
          npm -v
          echo "Multiline command finishes"
      - name: Python Command
        run: |
          import platform
          print(platform.processor())
        shell: python
